apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -apache-vm3

patches:
  - path: patch.yaml
    target:
      kind: VirtualMachine
      name: base-vm
