apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - target:
      kind: VirtualMachine
      name: base-vm
    patch: |-
      apiVersion: kubevirt.io/v1
      kind: VirtualMachine
      metadata:
        name: apache-vm1  # rename for this overlay
      spec:
        template:
          metadata:
            labels:
              kubevirt.io/domain: apache-vm1
