apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: base-vm
  namespace: vm-migration-test
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: base-vm
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - name: rootdisk
              disk:
                bus: virtio
          interfaces:              # <-- ADD THIS SECTION
            - name: default
              masquerade: {}
        resources:
          requests:
            memory: 2Gi
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/centos-stream:9
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: root
              password: password
              chpasswd: { expire: False }
              ssh_pwauth: True
      networks:
        - name: default
          pod: {}
